In [1]:
player = ['Federer', 'Nadal', 'Felix']
player

['Federer', 'Nadal', 'Felix']

In [2]:
player.append('Djokovic')


In [3]:
player


['Federer', 'Nadal', 'Felix', 'Djokovic']

In [4]:
player.append('Medvedev')
player.append('Sinner')
player

['Federer', 'Nadal', 'Felix', 'Djokovic', 'Medvedev', 'Sinner']

In [5]:
new_players = ['Tsitsipas', 'Rublev', 'Dimitrov']

In [6]:
player.extend(new_players)
player

['Federer',
 'Nadal',
 'Felix',
 'Djokovic',
 'Medvedev',
 'Sinner',
 'Tsitsipas',
 'Rublev',
 'Dimitrov']

In [7]:
player.remove('Medvedev')
player

['Federer',
 'Nadal',
 'Felix',
 'Djokovic',
 'Sinner',
 'Tsitsipas',
 'Rublev',
 'Dimitrov']

In [8]:
player[-1]

'Dimitrov'

In [9]:
new_list = player[-3:]
new_list

['Tsitsipas', 'Rublev', 'Dimitrov']

In [10]:
player[1:7:2]

['Nadal', 'Djokovic', 'Tsitsipas']

In [11]:
squares_list = []

for x  in range (101):
     if (x%2 != 0 and x >= 50): 
       squares_list.append(x*x)

squares_list

[2601,
 2809,
 3025,
 3249,
 3481,
 3721,
 3969,
 4225,
 4489,
 4761,
 5041,
 5329,
 5625,
 5929,
 6241,
 6561,
 6889,
 7225,
 7569,
 7921,
 8281,
 8649,
 9025,
 9409,
 9801]

In [12]:
filtered_players = [x for x in player  if 'e' in x]
filtered_players

['Federer', 'Felix', 'Sinner', 'Rublev']

In [13]:
max(squares_list)

9801

In [14]:
min(squares_list)

2601

In [15]:
sum(squares_list)

145825

In [16]:
len(squares_list)

25

In [17]:
squares_list.sort()


In [18]:
 numbers = [1, 37, 2, 59, 46, 32, 12, 40, 78]
 numbers.sort()
numbers.reverse()
numbers

[78, 59, 46, 40, 37, 32, 12, 2, 1]

In [19]:
import statistics

In [20]:
statistics.mean(numbers)

34.111111111111114

In [21]:
statistics.median(numbers)

37

In [22]:
import queue
from collections import deque

num = [2, -1, 3, 4, -1, 5, 6, 7, -1, 8, 9, 10, -1 , -1]
queue = deque(num)
print(queue)


deque([2, -1, 3, 4, -1, 5, 6, 7, -1, 8, 9, 10, -1, -1])


In [70]:
def reOrg(queue):
    solution = []
    temp = []

    while queue:
        num = queue.popleft()
        if num > 0:
            temp.append(num)
        else:
            if temp:
                solution.append(temp)
                temp = []
    
    if temp:
        solution.append(temp)
    
    return solution

queue = deque([2, -1, 3, 4, -1, 5, 6, 7, -1, 8, 9, 10, -1, -1])
print(reOrg(queue))

[[2], [3, 4], [5, 6, 7], [8, 9, 10]]


In [ ]:
# Sictionary exercise

In [87]:
score = {
    "1001":[95,93,81,90,100],
    "1002":[100,95,89,87],
    "1003":[92,91,None,80,None],
}
print(score)
score.keys()
score.get("1003")
del score['1001']
print(score)

{'1001': [95, 93, 81, 90, 100], '1002': [100, 95, 89, 87], '1003': [92, 91, None, 80, None]}
{'1002': [100, 95, 89, 87], '1003': [92, 91, None, 80, None]}


In [88]:
patient = {
    'bmi' : 30,
    'diagnosis' : ['Schizophrenia', 'Diabetes', 'Anxiety'],
    'heart_rates' : [95, 123, 135, 91, 175, 2000]
}

In [89]:
patient['medication'] = ['Aripiprazole', 'Citalopram', 'Ibuprofen']
print(patient)

{'bmi': 30, 'diagnosis': ['Schizophrenia', 'Diabetes', 'Anxiety'], 'heart_rates': [95, 123, 135, 91, 175, 2000], 'medication': ['Aripiprazole', 'Citalopram', 'Ibuprofen']}


In [90]:
patient['heart_rates'].sort()

In [104]:
print(patient)

{'bmi': 30, 'diagnosis': ['Schizophrenia', 'Diabetes', 'Anxiety'], 'heart_rates': [91, 95, 123, 135, 175, 2000], 'medication': ['Aripiprazole', 'Citalopram', 'Ibuprofen']}


In [105]:
print(patient)

{'bmi': 30, 'diagnosis': ['Schizophrenia', 'Diabetes', 'Anxiety'], 'heart_rates': [91, 95, 123, 135, 175, 2000], 'medication': ['Aripiprazole', 'Citalopram', 'Ibuprofen']}


In [111]:
while 2000 in patient['heart_rates']:
  patient['heart_rates'].remove(2000)

In [112]:
print(patient)

{'bmi': 30, 'diagnosis': ['Schizophrenia', 'Diabetes', 'Anxiety'], 'heart_rates': [91, 95, 123, 135, 175], 'medication': ['Aripiprazole', 'Citalopram', 'Ibuprofen']}


In [115]:
patient['bmi'] +=5

In [116]:
print(patient)

{'bmi': 35, 'diagnosis': ['Schizophrenia', 'Diabetes', 'Anxiety'], 'heart_rates': [91, 95, 123, 135, 175], 'medication': ['Aripiprazole', 'Citalopram', 'Ibuprofen']}


In [ ]:
#code for Heap exercice

In [117]:
list = [22, 37, 90, 49, 56, 65]
list

[22, 37, 90, 49, 56, 65]

In [119]:
import heapq
heapq.heapify(list)
list

[22, 37, 65, 49, 56, 90]

In [121]:
heapq.heappush(list,12)
heapq.heappush(list,40)
heapq.heappush(list,99)
print(list)

[12, 37, 22, 40, 56, 90, 65, 49, 99]


In [130]:
heapq.heappop(list)
heapq.heappop(list)
heapq.heappop(list)
heapq.heappop(list)

IndexError: index out of range

In [131]:
list = [12, 37, 22, 40, 56, 90, 65, 49, 99]
neg = [-x for x in list]
print(neg)

[-12, -37, -22, -40, -56, -90, -65, -49, -99]


In [133]:
heapq.heapify(neg)
neg

[-99, -56, -90, -49, -12, -22, -65, -37, -40]

In [134]:
list = [-x for x in neg]
list

[99, 56, 90, 49, 12, 22, 65, 37, 40]

In [135]:


#code for Numpy area

In [137]:
pip install numpy


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 14.2 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [139]:
import numpy as np
list = [[1,2,3],[10,20,30],[100,200,300]]
twoDArr = np.array(list)
print(twoDArr)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [140]:
twoDArr.ndim

2

In [141]:
twoDArr.shape

(3, 3)

In [142]:
twoDArr.size

9

In [143]:
twoDArr.dtype

dtype('int64')

In [144]:
twoDArr.data